# Generated by Django 3.2.21 on 2023-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
